"""Central package/audit policy for the macOS CI build."""

VULKAN_SDK_TAG = "vulkan-sdk-1.4.350.0"
VULKAN_SDK_VERSION = "1.4.350"

MPV_FEATURES = [
    "caca",
    "cdda",
    "cocoa",
    "coreaudio",
    "dvdnav",
    "gl",
    "gl-cocoa",
    "iconv",
    "javascript",
    "jpeg",
    "lcms2",
    "libarchive",
    "libavdevice",
    "libbluray",
    "luajit",
    "macos-cocoa-cb",
    "macos-media-player",
    "macos-touchbar",
    "openal",
    "rubberband",
    "sdl2-audio",
    "sdl2-gamepad",
    "sdl2-video",
    "swift",
    "uchardet",
    "vapoursynth",
    "videotoolbox-gl",
    "videotoolbox-pl",
    "vulkan",
    "zimg",
    "zlib",
]

MPV_BUILD_OPTIONS = [
    ("plain-gl", "enabled"),
]

HOMEBREW_BUILD_TOOLS = [
    "autoconf",
    "automake",
    "cargo-c",
    "cmake",
    "curl",
    "gettext",
    "git",
    "libtool",
    "lld",
    "llvm",
    "luarocks",
    "meson",
    "mono",
    "nasm",
    "ninja",
    "pkgconf",
    "python",
    "rust",
]

FORBIDDEN_HOMEBREW_RUNTIME_FORMULAS = [
    "ffmpeg",
    "libass",
    "libplacebo",
    "fdk-aac",
    "frei0r",
    "chromaprint",
    "libvmaf",
    "librsvg",
    "openh264",
    "openjpeg",
    "snappy",
    "libvidstab",
    "vapoursynth",
    "x264",
    "x265",
]

PKG_CONFIG_PACKAGES = [
    "aom",
    "caca",
    "libchromaprint",
    "davs2",
    "dovi",
    "dvdnav",
    "fdk-aac",
    "frei0r",
    "libarchive",
    "libass",
    "libavcodec",
    "libavdevice",
    "libavfilter",
    "libavformat",
    "libavutil",
    "libbluray",
    "libbs2b",
    "libcdio",
    "libcdio_cdda",
    "libcdio_paranoia",
    "libopenjp2",
    "openh264",
    "libjpeg",
    "kvazaar",
    "libmysofa",
    "libplacebo",
    "libunibreak",
    "libswresample",
    "libswscale",
    "libvmaf",
    "libvvenc",
    "libzstd",
    "lcms2",
    "librsvg-2.0",
    "librtmp",
    "luajit",
    "mujs",
    "openal",
    "rav1e",
    "rubberband",
    "sdl2",
    "snappy",
    "theora",
    "uavs3d",
    "uchardet",
    "vapoursynth",
    "vapoursynth-script",
    "vidstab",
    "vulkan",
    "zimg",
    "zlib",
    "zvbi-0.2",
]

SOURCE_PREFIX_PACKAGES = [
    "dovi",
    "libplacebo",
    "libbs2b",
    "davs2",
    "uavs3d",
    "kvazaar",
    "vulkan",
    "zimg",
    "zvbi-0.2",
]

VCPKG_PREFIX_PACKAGES = [
    "libass",
    "libmysofa",
    "libunibreak",
    "libvmaf",
    "libvvenc",
]

FFMPEG_PREFIX_PACKAGES = [
    "libavcodec",
    "libavdevice",
    "libavfilter",
    "libavformat",
    "libavutil",
    "libswresample",
    "libswscale",
]

STATIC_PKG_CONFIG_PACKAGES = [
    "libavcodec",
    "libavformat",
    "libavfilter",
    "libplacebo",
    "libass",
    "libunibreak",
    "libbs2b",
    "libchromaprint",
    "libopenjp2",
    "openh264",
    "kvazaar",
    "snappy",
    "librtmp",
    "theora",
    "libvmaf",
    "librsvg-2.0",
    "libvvenc",
    "caca",
    "libcdio",
    "libcdio_paranoia",
    "dovi",
    "zimg",
]

FFMPEG_FLAGS = [
    ("static", "--enable-static"),
    ("no shared libraries", "--disable-shared"),
    ("static pkg-config", "--pkg-config-flags=--static"),
    ("pic", "--enable-pic"),
    ("hardcoded tables", "--enable-hardcoded-tables"),
    ("debug disabled", "--disable-debug"),
    ("stripping enabled", "--enable-stripping"),
    ("pthreads", "--enable-pthreads"),
    ("OS/2 threads disabled", "--disable-os2threads"),
    ("Win32 threads disabled", "--disable-w32threads"),
    ("assembly", "--enable-asm"),
    ("aom", "--enable-libaom"),
    ("bzip2", "--enable-bzlib"),
    ("chromaprint", "--enable-chromaprint"),
    ("dash demuxer", "--enable-demuxer=dash"),
    ("dav1d", "--enable-libdav1d"),
    ("davs2", "--enable-libdavs2"),
    ("fdk-aac", "--enable-libfdk-aac"),
    ("frei0r", "--enable-frei0r"),
    ("game-music-emu", "--enable-libgme"),
    ("gray", "--enable-gray"),
    ("HTML docs disabled", "--disable-htmlpages"),
    ("iconv", "--enable-iconv"),
    ("jpeg-xl", "--enable-libjxl"),
    ("kvazaar", "--enable-libkvazaar"),
    ("lame", "--enable-libmp3lame"),
    ("libaribcaption", "--enable-libaribcaption"),
    ("libcaca", "--enable-libcaca"),
    ("libcdio", "--enable-libcdio"),
    ("libmysofa", "--enable-libmysofa"),
    ("libopenh264", "--enable-libopenh264"),
    ("libopenjpeg", "--enable-libopenjpeg"),
    ("libopenmpt", "--enable-libopenmpt"),
    ("libplacebo", "--enable-libplacebo"),
    ("librsvg", "--enable-librsvg"),
    ("librtmp", "--enable-librtmp"),
    ("librubberband", "--enable-librubberband"),
    ("libshaderc", "--enable-libshaderc"),
    ("libsnappy", "--enable-libsnappy"),
    ("libsoxr", "--enable-libsoxr"),
    ("libssh", "--enable-libssh"),
    ("libtheora", "--enable-libtheora"),
    ("libvidstab", "--enable-libvidstab"),
    ("libvmaf", "--enable-libvmaf"),
    ("libvpx", "--enable-libvpx"),
    ("libvorbis", "--enable-libvorbis"),
    ("libvvenc", "--enable-libvvenc"),
    ("libzvbi", "--enable-libzvbi"),
    ("macOS kperf", "--enable-macos-kperf"),
    ("man docs disabled", "--disable-manpages"),
    ("openal", "--enable-openal"),
    ("opencl", "--enable-opencl"),
    ("opengl", "--enable-opengl"),
    ("openssl", "--enable-openssl"),
    ("nonfree", "--enable-nonfree"),
    ("opus", "--enable-libopus"),
    ("pod docs disabled", "--disable-podpages"),
    ("rav1e", "--enable-librav1e"),
    ("sdl2", "--enable-sdl2"),
    ("speex", "--enable-libspeex"),
    ("srt", "--enable-libsrt"),
    ("svt-av1", "--enable-libsvtav1"),
    ("text docs disabled", "--disable-txtpages"),
    ("uavs3d", "--enable-libuavs3d"),
    ("vapoursynth", "--enable-vapoursynth"),
    ("audiotoolbox", "--enable-audiotoolbox"),
    ("videotoolbox", "--enable-videotoolbox"),
    ("vulkan", "--enable-vulkan"),
    ("lto", "--enable-lto"),
    ("webp", "--enable-libwebp"),
    ("x264", "--enable-libx264"),
    ("x265", "--enable-libx265"),
    ("xvid", "--enable-libxvid"),
    ("xz", "--enable-lzma"),
    ("zlib", "--enable-zlib"),
]

FFMPEG_RUNTIME_CHECKS = [
    ("-encoders", "FFmpeg encoder: libfdk_aac", r"(^|[ \t])libfdk_aac([ \t]|$)"),
    ("-decoders", "FFmpeg decoder: libfdk_aac", r"(^|[ \t])libfdk_aac([ \t]|$)"),
    ("-encoders", "FFmpeg encoder: libkvazaar", r"(^|[ \t])libkvazaar([ \t]|$)"),
    ("-encoders", "FFmpeg encoder: libopenh264", r"(^|[ \t])libopenh264([ \t]|$)"),
    ("-encoders", "FFmpeg encoder: libopenjpeg", r"(^|[ \t])libopenjpeg([ \t]|$)"),
    ("-encoders", "FFmpeg encoder: libtheora", r"(^|[ \t])libtheora([ \t]|$)"),
    ("-encoders", "FFmpeg encoder: libvvenc", r"(^|[ \t])libvvenc([ \t]|$)"),
    ("-muxers", "FFmpeg muxer: chromaprint", r"(^|[ \t])chromaprint([ \t]|$)"),
    ("-demuxers", "FFmpeg demuxer: dash", r"(^|[ \t])dash([ \t]|$)"),
    ("-filters", "FFmpeg filter: frei0r", r"(^|[ \t])frei0r([ \t]|$)"),
    ("-filters", "FFmpeg filter: libvmaf", r"(^|[ \t])libvmaf([ \t]|$)"),
    ("-hwaccels", "FFmpeg hwaccel: vulkan", r"(?m)^vulkan$"),
    ("-filters", "FFmpeg filter: scale_vulkan", r"(^|[ \t])scale_vulkan([ \t]|$)"),
    ("-filters", "FFmpeg filter: vidstabdetect", r"(^|[ \t])vidstabdetect([ \t]|$)"),
    ("-filters", "FFmpeg filter: vidstabtransform", r"(^|[ \t])vidstabtransform([ \t]|$)"),
    ("-devices", "FFmpeg output device: audiotoolbox", r"(^|[ \t])audiotoolbox([ \t]|$)"),
]

SOURCE_REVISION_ITEMS = [
    "vcpkg",
    "dovi_tool",
    "Vulkan-Headers",
    "libplacebo",
    "davs2",
    "uavs3d",
    "zvbi",
    "zimg",
    "game-music-emu",
    "libbs2b",
    "libcaca",
    "libcdio",
    "libcdio-paranoia",
    "Vulkan-Loader",
    "MoltenVK",
    "rav1e",
    "vid.stab",
    "kvazaar",
    "frei0r",
    "vapoursynth",
    "ffmpeg",
]

APPLIED_PATCHES = [
    "cmake/ports-overlay/libass/0001-try-to-parse-script-properties.patch",
    "cmake/ports-overlay/libunibreak/fix_export.patch",
    "patch/davs2-0001-skip-lto-sensitive-endian-probe-on-macos-arm64.patch",
    "patch/libplacebo-0001-colorspace-do-not-force-pq-transfer-to-zero-nits-black-always.patch",
    "patch/libplacebo-0002-revert-renderer-never-use-linear-downscaling-on-hdr-sources.patch",
    "patch/libcdio-paranoia-0001-build-libraries-only.patch",
    "patch/libbs2b-0001-build-library-without-sndfile-tools.patch",
    "patch/ffmpeg-0001-avformat-some-subtitle-optimizations.patch",
    "patch/ffmpeg-0002-avformat-spdifenc-handle-long-TrueHD-input_timing.patch",
    "patch/ffmpeg-0003-fftools-rename-dec-init.patch",
    "patch/ffmpeg-0004-avcodec-apv-parser-rename-close-callback.patch",
    "cmake/ports-overlay/x264/prealloc-strict-aliasing.patch",
    "cmake/ports-overlay/x264/mbtree-propagate-list-tail.patch",
    "cmake/ports-overlay/x264/cavlc-aarch64-coeff-level-run.patch",
    "cmake/ports-overlay/libvmaf/no-internal-close-symbols.patch",
    "cmake/ports-overlay/vvenc/vvenc-0001-explicitly-instantiate-loopfilter-deblockarea.patch",
]

MAPPED_DECISIONS = [
    ("LuaSocket", "PLUGIN EXCEPTION", "Source-built through LuaRocks against source-built LuaJIT; bundled as runtime module."),
    ("VapourSynth", "PLUGIN EXCEPTION", "Source-built runtime/API exception; libvsscript stays dynamic and is published through rpath."),
    ("frei0r", "PLUGIN EXCEPTION", "Source-built frei0r plugins are allowed as runtime plugin files."),
    ("FFmpeg install prefix", "SEPARATE ARTIFACT", "FFmpeg installs to `{FFMPEG_PREFIX}`; mpv consumes its static pkg-config metadata from that prefix."),
    (
        "Rust staticlib overlap",
        "STATIC LINKAGE HYGIENE",
        "`libdovi.a` and `librav1e.a` keep their public C APIs while overlapping Rust runtime "
        "symbols are weakened before FFmpeg links both archives.",
    ),
    ("OpenCL", "SYSTEM DYNAMIC", "FFmpeg uses Apple's OpenCL framework; it is not treated as a third-party Homebrew dependency."),
    (
        "libiconv",
        "SYSTEM DYNAMIC",
        "macOS uses Apple's libiconv; mpv Meson receives explicit iconv link flags because the pinned "
        "vcpkg libiconv port is an empty wrapper on macOS.",
    ),
    ("LLVM C++ runtime", "RUNTIME EXCEPTION", "Homebrew LLVM libc++, libc++abi, and libunwind are the only allowed Homebrew runtime dylibs; mpv.app bundles copies in Contents/Frameworks."),
    ("Vulkan runtime", "RUNTIME EXCEPTION", "Source-built Vulkan loader and MoltenVK dylibs are bundled as the only allowed non-plugin third-party dynamic runtime exception."),
    ("ANGLE", "MAPPED", "macOS build uses Cocoa/OpenGL plus Vulkan/MoltenVK instead of Win32 ANGLE."),
    ("amf-headers", "NOT APPLICABLE", "AMD AMF is Windows-specific here; macOS hardware decode path is VideoToolbox."),
    ("avisynth-headers", "MAPPED", "VapourSynth is source-built and required instead."),
    ("nvcodec-headers", "NOT APPLICABLE", "NVIDIA NVDEC/NVENC headers are not a macOS arm64 target; macOS uses VideoToolbox."),
    ("libvpl", "NOT APPLICABLE", "Intel VPL/QSV is not the macOS arm64 target path; macOS uses VideoToolbox."),
    ("OpenSSL winstore", "NOT APPLICABLE", "Windows certificate store patch is not a macOS target path."),
    ("mpv Windows package SHA patch", "NOT APPLICABLE", "Windows CMake package renaming is not used by this macOS workflow."),
    ("x265 multilib", "MAPPED", "Static macOS arm64 source build is retained; Windows-style multilib is not applicable."),
    ("Apple system libraries", "SYSTEM DYNAMIC", "`/System/Library`, `/usr/lib`, and Apple frameworks may remain dynamically linked."),
]

VULKAN_HEADERS_CONFIG_PATH = "{SOURCE_PREFIX}/share/cmake/VulkanHeaders/VulkanHeadersConfig.cmake"
VULKAN_HEADERS_CONFIG_VERSION_PATH = "{SOURCE_PREFIX}/share/cmake/VulkanHeaders/VulkanHeadersConfigVersion.cmake"
VULKAN_HEADERS_REGISTRY_XML_PATH = "{SOURCE_PREFIX}/share/vulkan/registry/vk.xml"

VULKAN_RUNTIME_SOURCE_GLOBS = [
    "{SOURCE_PREFIX}/lib/libvulkan*.dylib",
    "{SOURCE_PREFIX}/lib/libMoltenVK*.dylib",
    "{SOURCE_PREFIX}/share/vulkan/icd.d/*.json",
]

VULKAN_RUNTIME_FFMPEG_GLOBS = [
    "{FFMPEG_PREFIX}/lib/libvulkan*.dylib",
    "{FFMPEG_PREFIX}/lib/libMoltenVK*.dylib",
    "{FFMPEG_PREFIX}/share/vulkan/icd.d/*.json",
]

BUNDLE_ALLOWED_RUNTIME_EXCEPTION_PATTERNS = [
    r"libc\+\+(\.1)?\.dylib",
    r"libc\+\+abi(\.1)?\.dylib",
    r"libunwind(\.1)?\.dylib",
    r"libvulkan(\.[0-9]+)*\.dylib",
    r"libMoltenVK(\.[0-9]+)*\.dylib",
]

BUNDLE_DENY_DYLIB_PATTERNS = [
    "libaom",
    "libarchive",
    "libass",
    "libavcodec",
    "libavdevice",
    "libavfilter",
    "libavformat",
    "libavutil",
    "libbluray",
    "libbs2b",
    "libcaca",
    "libchromaprint",
    "libdav1d",
    "libdavs2",
    "libdovi",
    "libdvdnav",
    "libdvdread",
    "libfdk-aac",
    "libfreetype",
    "libfribidi",
    "libharfbuzz",
    "libjxl",
    "libkvazaar",
    "libluajit",
    "libmysofa",
    "libopenh264",
    "libopenjpeg",
    "libopenjp2",
    "libplacebo",
    "libpostproc",
    "librav1e",
    "librsvg",
    "librtmp",
    "librubberband",
    "libsnappy",
    "libswresample",
    "libswscale",
    "libtheora",
    "libuavs3d",
    "libunibreak",
    "libvidstab",
    "libvmaf",
    "libvpx",
    "libvvenc",
    "libx264",
    "libx265",
    "libzimg",
    "libzvbi",
]
